### ISSUE TITLE
Where you at on this project?

### ISSUE THREAD

**Issue by nstanard** [leapingfish/simple-modal-es6#2]
Was about to start working on my own ES6 modal to use with my webpack project. Just wanted to touch base and see if this was already a few steps ahead and in good shape for me to use.

**Comment by nstanard** [comment]
Just was curious why you mentioned it wasn't production ready.

**Comment by leapingfish** [comment]
@nstanard sorry for the delay in response to this. I just got this up and going and am about to launch it into a large production site. There is one bug where the event listener to remove is sometime left behind but otherwise I think it is starting to shape up nicely.

**Comment by leapingfish** [comment]
I said it was not production ready because while it works it had a few bugs, I wouldn't want anyone to become dependent on the project until I had full faith in it.
